 'bella nyanyi di rumah budi',
            'bapak joget pakai sarung',
            'rachel makan roti jatuh',
            'kak angel lompat sambil nangis',
            'mamak baca koran terbalik',
            'bou mery takut balon meletus',
            'kakak aulia lari keliling kursi',
            'bapak jatuh dari bangku',
            'bella ketawa sampai nangis',
            'rachel siram bunga kebanyakan air',
            'kak angel joget balon sabun',
            'mamak nyanyi suara cempreng',
            'bou mery makan donat besar',
            'bapak beli bakso pedas banget',
            'kakak aulia main boneka kelinci',
            'rachel tidur sambil ngorok',
            'bella lompat ke kasur empuk',
            'bapak baca buku kebalik',
            'mamak makan mie kepedasan',
            'kak angel baca buku pink',
            'bou mery nyanyi sambil lompat',
            'bella takut boneka panda',
            'kakak aulia joget di teras',
            'rachel ketawa keras banget',
            'bapak lompat sambil pegang sandal',
            'mamak siram bunga pagi',
            'bou mery joget di dapur',
            'kak angel nyanyi nada tinggi',
            'bella baca buku tebal',
            'rachel makan roti coklat',
            'bapak tidur sambil ngorok',
            'kakak aulia lompat jungkir balik',
            'mamak jatuh duduk lucu',
            'bou mery baca buku tipis',
            'kak angel main balon sabun',
            'rachel joget keliling rumah',
            'bella makan donat warna-warni',
            'bapak ketawa sambil pegang perut',
            'kakak aulia siram bunga kuning',
            'mamak beli donat kepedasan',
            'bou mery lompat ke sofa',
            'rachel nyanyi sambil ketawa',
            'kak angel lompat di kasur',
            'bapak makan mie panas banget',
            'bella joget sambil ketawa',
            'mamak lari keliling rumah',
            'kakak aulia baca buku besar',
            'rachel takut kucing gendut',
            'bou mery ketawa jungkir balik',
            'bapak nyanyi suara sumbang',
            'kak angel tidur sambil senyum',
            'bella siram bunga sore',
            'mamak joget balon sabun',
            'kakak aulia lompat sambil ketawa',
            'bapak baca buku tipis',
            'rachel lompat sambil tertawa',
            'bou mery makan mie kebanyakan',
            'kak angel ketawa ngakak keras',
            'bella nyanyi suara cempreng',
            'mamak makan roti isi coklat'


            WritingPage.module.css


            import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import Header from '../../components/Header/Header';
import styles from './WritingPage.module.css'