

     { sentence: 'Kucing makan.', audio: '/sounds/kalimat2.mp3' },
    { sentence: 'Bunga itu indah.', audio: '/sounds/kalimat3.mp3' },
    { sentence: 'Ayah membaca buku.', audio: '/sounds/kalimat4.mp3' },
    { sentence: 'Ibu memasak nasi.', audio: '/sounds/kalimat5.mp3' },
    { sentence: 'Adik bermain boneka.', audio: '/sounds/kalimat6.mp3' },
    { sentence: 'Kakak pergi sekolah.', audio: '/sounds/kalimat7.mp3' },
    { sentence: 'Burung bernyanyi merdu.', audio: '/sounds/kalimat8.mp3' },
    { sentence: 'Matahari bersinar terang.', audio: '/sounds/kalimat9.mp3' },
    { sentence: 'Ayam makan jagung.', audio: '/sounds/kalimat10.mp3' },
    { sentence: 'Baju ini warna biru.', audio: '/sounds/kalimat11.mp3' },
    { sentence: 'Saya suka buah apel.', audio: '/sounds/kalimat12.mp3' },
    { sentence: 'Pohon itu sangat tinggi.', audio: '/sounds/kalimat13.mp3' },
    { sentence: 'Kereta api melaju cepat.', audio: '/sounds/kalimat14.mp3' },
    { sentence: 'Anjing itu lucu sekali.', audio: '/sounds/kalimat15.mp3' },
    { sentence: 'Kupu-kupu terbang tinggi.', audio: '/sounds/kalimat16.mp3' },
    { sentence: 'Bulan bersinar di malam hari.', audio: '/sounds/kalimat17.mp3' },
    { sentence: 'Nenek bercerita dongeng.', audio: '/sounds/kalimat18.mp3' },
    { sentence: 'Kakek duduk di kursi.', audio: '/sounds/kalimat19.mp3' },
    { sentence: 'Sepeda motor melaju kencang.', audio: '/sounds/kalimat20.mp3' },
    { sentence: 'Baju merah itu bagus.', audio: '/sounds/kalimat21.mp3' },
    { sentence: 'Saya punya banyak teman.', audio: '/sounds/kalimat22.mp3' },
    { sentence: 'Anak-anak bermain di taman.', audio: '/sounds/kalimat23.mp3' },
    { sentence: 'Pelangi itu warna-warni.', audio: '/sounds/kalimat24.mp3' },
    { sentence: 'Air sungai mengalir jernih.', audio: '/sounds/kalimat25.mp3' },
    { sentence: 'Buku cerita itu seru.', audio: '/sounds/kalimat26.mp3' },
    { sentence: 'Langit cerah hari ini.', audio: '/sounds/kalimat27.mp3' },
    { sentence: 'Mobil itu melaju pelan.', audio: '/sounds/kalimat28.mp3' },
    { sentence: 'Rumah saya dekat sekolah.', audio: '/sounds/kalimat29.mp3' },
    { sentence: 'Kami makan bersama keluarga.', audio: '/sounds/kalimat30.mp3' },





     { word: 'Buku', audio: '/sounds/buku.mp3' },
    { word: 'Kursi', audio: '/sounds/kursi.mp3' },
    { word: 'Pensil', audio: '/sounds/pensil.mp3' },
    { word: 'Rumah', audio: '/sounds/rumah.mp3' },
    { word: 'Pintu', audio: '/sounds/pintu.mp3' },
    { word: 'Jendela', audio: '/sounds/jendela.mp3' },
    { word: 'Makan', audio: '/sounds/makan.mp3' },
    { word: 'Minum', audio: '/sounds/minum.mp3' },
    { word: 'Tidur', audio: '/sounds/tidur.mp3' },
    { word: 'Mandi', audio: '/sounds/mandi.mp3' },
    { word: 'Sekolah', audio: '/sounds/sekolah.mp3' },
    { word: 'Guru', audio: '/sounds/guru.mp3' },
    { word: 'Murid', audio: '/sounds/murid.mp3' },
    { word: 'Pulpen', audio: '/sounds/pulpen.mp3' },
    { word: 'Tas', audio: '/sounds/tas.mp3' },
    { word: 'Sepatu', audio: '/sounds/sepatu.mp3' },
    { word: 'Kaos', audio: '/sounds/kaos.mp3' },
    { word: 'Baju', audio: '/sounds/baju.mp3' },
    { word: 'Celana', audio: '/sounds/celana.mp3' },
    { word: 'Topi', audio: '/sounds/topi.mp3' },
    { word: 'Mata', audio: '/sounds/mata.mp3' },
    { word: 'Hidung', audio: '/sounds/hidung.mp3' },
    { word: 'Mulut', audio: '/sounds/mulut.mp3' },
    { word: 'Tangan', audio: '/sounds/tangan.mp3' },
    { word: 'Kaki', audio: '/sounds/kaki.mp3' },
    { word: 'Rambut', audio: '/sounds/rambut.mp3' },
    { word: 'Gigi', audio: '/sounds/gigi.mp3' },
    { word: 'Mobil', audio: '/sounds/mobil.mp3' },
    { word: 'Motor', audio: '/sounds/motor.mp3' },
